#!/bin/bash
# Node Settings
#########################setting####################
env=online
port=8000
uid=api.acgo.club
appPath=/home/website/App/$uid
logPath=/home/website/Logs/$uid
#########################env setting####################
export NODE_ENV=$env
export NODE_PORT=$port
export APP_PATH=$appPath
export LOG_PATH=$logPath
#########################addapp####################
addapp() {
  echo add app begin
    export NODE_INIT_CASE=addapp
    export NODE_INIT_PNAME=$2
    export NODE_INIT_ALIAS=$3
    export NODE_INIT_UNAME=$4
    export NODE_INIT_EMAIL=$5
    su -p website -c "node $appPath/init.js"
  echo add app end
}
#########################addcode####################
addcode(){
  echo add code begin
    export NODE_INIT_CASE=code
    node $appPath/init.js
  echo add code end
}
#########################starting####################
start() {
  echo start begin
    pm2 start $appPath/bin/www -n $uid -l $logPath/log.log -e $logPath/error.log
  echo start end
}
#########################status####################
status(){
  echo status begin
    pm2 show $uid
  echo status end
}
#########################stoping####################
stop() {
  echo stop begin
    pm2 stop $uid
  echo stop end
}
#########################restart####################
restart(){
  echo restart begin
    stop
    start
  echo restart end
}

case "$1" in
  addapp)
        addapp
        ;;
  addcode)
        addcode
        ;;
  start)
        start
        ;;
  status)
        status
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  ?|help)
        echo $"Usage: $0 {addapp|addcode|start|status|stop|restart|help|?}"
        ;;
  *)
        echo $"Usage: $0 {help|?}"
esac